import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionProvider from "./components/SessionProvider";
import { getServerSession } from "next-auth";
import MyLayout from "./components/MyLayout";

export const metadata: Metadata = {
  title: {
    default: "Spotify-clone",
    template: "%s | Spotify-clone",
  },
  description: "Generated by Dmytro Tarasenko",
};
const inter = Inter({ subsets: ["latin"] });

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <link
        rel="icon"
        href="https://open.spotifycdn.com/cdn/images/favicon32.b64ecc03.png"
        sizes="any"
      />
      <body className={inter.className}>
        <SessionProvider session={session}>
          <MyLayout>{children}</MyLayout>
        </SessionProvider>
      </body>
    </html>
  );
}
